### ISSUE TITLE
Should we implement exit codes?

### ISSUE THREAD

**Issue by clubdeuce** [wplib/box-scripts#10]
Commands can fail, and therefore we should implement return codes so that the API can know whether the command succeeded or not.

**Comment by mikeschinkel** [comment]
So, yes, definitely. 

Realizing I am currently working through and learning Bash best practices as I go so I don't yet know how to do everything the best possible.  One thing I think we need to develop is a consistent strategy for handling error codes as I do not know what that should be yet.

Speaking of error handling I learned about [Bash Exit Traps](http://stackoverflow.com/questions/64786/error-handling-in-bash) recently and plan to [incorporate these into the CLI](http://redsymbol.net/articles/bash-exit-traps/) moving forward
